// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thymkjtnggytmiemzenp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoeW1ranRuZ2d5dG1pZW16ZW5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTU4NjYsImV4cCI6MjA2MjM3MTg2Nn0.H_Bg8r2QGd6YPDOofp_AHsQblugJNrJ_zQ-3cFxqvzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);